module.exports = {
  JobState: {
    JOB_STATE_UNKNOWN: "JOB_STATE_UNKNOWN",
    JOB_STATE_PENDING: "JOB_STATE_PENDING",
    JOB_STATE_RUNNING: "JOB_STATE_RUNNING",
    JOB_STATE_STOPPED: "JOB_STATE_STOPPED",
  },
  JobStatus: {
    JOB_STATUS_UNKNOWN: "JOB_STATUS_UNKNOWN",
    JOB_STATUS_HEALTHY: "JOB_STATUS_HEALTHY",
    JOB_STATUS_FAULTED: "JOB_STATUS_FAULTED",
    JOB_STATUS_CANCELED: "JOB_STATUS_CANCELED",
  },
};
